version: "3"
networks:
    frontend:
        driver: overlay
        external: true
    backend:
        driver: overlay
        external: true

services:
    db:
        image: postgres:9.4
        deploy:
            replicas: 1
            placement:
                constraints: [node.role != manager]
        networks:
            - backend
        volumes:
            - db-data:/var/lib/postgresql/data
    result-app:
        image: bretfisher/examplevotingapp_result
        deploy:
            replicas: 1
            placement:
                constraints: [node.hostname == worker02]
        ports:
            - 5001:80
        depends_on:
            - db
        networks:
            - backend

    redis:
        image: redis:3.2
        deploy:
            replicas: 1
            placement:
                constraints: [node.role != manager]
        networks:
            - frontend
      worker:
        image: bretfisher/examplevotingapp_worker:java
        deploy:
            replicas: 1
            placement:
                constraints: [node.role != manager]
        depends_on:
            - redis
        networks:
            - frontend
            - backend
    voting-app:
        image: bretfisher/examplevotingapp_vote
        ports:
            - 8000:80
        deploy:
            replicas: 3
            placement:
                constraints: [node.hostname == worker01]
        depends_on:
            - worker
        networks:
            - frontend

volumes:
    db-data: